### ISSUE TITLE
unable to execute cloudtracker commands

### ISSUE THREAD

**Issue by vinaykmatam** [duo-labs/cloudtracker#82]
(venv) ➜  ~ cloudtracker --account demo --list users
Traceback (most recent call last):
  File "/Users/apple/venv/bin/cloudtracker", line 8, in <module>
    sys.exit(main())
  File "/Users/apple/venv/lib/python3.10/site-packages/cloudtracker/cli.py", line 97, in main
    config = yaml.load(args.config)
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/apple/venv/lib/python3.10/site-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
(venv) ➜  ~

When i tried to run the cloudtracker commands the above error encounter's

**Comment by harshitpotter** [comment]
Run with Python3.8 venv

**Comment by Almenon** [comment]
You need to run w/ 3.7, see https://github.com/duo-labs/cloudtracker/issues/83
